### PR TITLE
 get stream by id new one

### PR DESCRIPTION
**Pull request by jw0711qt**
@YoussefMIbrahim @cjdufault @haselfine 
 my work for current stream by game id the one it was merged it's not any more in the twich.py. I had a confusion in my vs code and then after my vs code asked me to stash or to merge to master , I did git stash and then my work removed from twich.py. please check it now.

### CODE REVIEW

**Review by cjdufault — COMMENTED** [review]
What does this do that the existing [twitch.py](https://github.com/haselfine/capstone_project_4/blob/5c5e91e61549973484b5411d07fdeb47789126ae/view/twitch.py#L25-L54) doesn't do?

**Comment by jw0711qt** [comment]
@Dufault, Connor J<mailto:connor.dufault@go.minneapolis.edu>
This was in the twitch.py first of all . Second thing Clara   Already posted on announcement when we submit  project 4 we have to tell her what we did in the project individual , so bro I have to get my grade too.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by haselfine** [comment]
@jw0711qt Just because it got updated doesn't mean she'll lower your grade. She'll see the commits you made in the contributers section and elsewhere. No reason to fret about this particular piece of code.

**Comment by jw0711qt** [comment]
@Haseltine, Benjamin D<mailto:benjamin.haseltine@go.minneapolis.edu>
Thank you for letting me know, I thought I stashed what I did, because it disappeared from my vs code after I did git stash.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by claraj** [comment]
@jw0711qt I'm looking at the entire history of your project and every file is labeled with who did what, and its history. So if you did work and someone else added or modified, then your contribution is still preserved.

**Pull request closed without merging**
